// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.loadImage = function(url) {
      return $.Deferred(function(deferred) {
        var image;
        image = new Image();
        image.src = url;
        image.onload = function() {
          return deferred.resolve(image);
        };
        return image.onerror = function() {
          return deferred.reject("Unable to load " + url);
        };
      }).promise();
    };
    $.loadImages = function(arr) {
      return $.Deferred(function(deferred) {
        var images, url, _i, _len, _results;
        images = [];
        _results = [];
        for (_i = 0, _len = arr.length; _i < _len; _i++) {
          url = arr[_i];
          _results.push($.loadImage(url).then(function(image) {
            images.push(image);
            if (images.length === arr.length) {
              return deferred.resolve(images);
            }
          }).fail(function(err) {
            return deferred.reject(err);
          }));
        }
        return _results;
      }).promise();
    };
    return $.loadImages(['./images/asteroid1.png', './images/asteroid2.png', './images/asteroid3.png']).then(function(images) {
      var canvas, ctx;
      canvas = $('#gameScreen')[0];
      ctx = canvas.getContext('2d');
      return setInterval((function() {
        var i, image, _i, _len, _results;
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        i = 0;
        _results = [];
        for (_i = 0, _len = images.length; _i < _len; _i++) {
          image = images[_i];
          ctx.drawImage(image, 100 * i, 0);
          _results.push(i++);
        }
        return _results;
      }), 1000);
    }).fail(function(err) {
      return console.debug(err);
    });
  });

}).call(this);
